name: bullpen_signal
version: 0.1.0
config-version: 2

profile: bullpen_signal_local

model-paths:
  - models
test-paths:
  - tests
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  bullpen_signal:
    silver:
      +schema: silver
    marts:
      +schema: marts

seeds:
  bullpen_signal:
    +schema: seeds
    player_handedness:
      +column_types:
        player_id: bigint
        role: varchar
        hand: varchar
    leverage_index_tango:
      +column_types:
        inning: integer
        half_inning: varchar
        on_1b: integer
        on_2b: integer
        on_3b: integer
        outs: integer
        score_diff: integer
        leverage_index: double
    player_names:
      +column_types:
        player_id: bigint
        name_last: varchar
        name_first: varchar
