"""Load the Statcast-abbreviation to team_id reference map.

The CSV at reference/team_abbreviations.csv is generated by
build_team_abbreviation_map.py from observed game data. This module
reads it once and exposes a dict for the mapping layer.

The map is loaded lazily and cached at module level so repeated
row_to_pitch_event calls do not re-read the file. The map is small
(30 teams) and static within a process.
"""

from __future__ import annotations

import csv
from functools import lru_cache
from pathlib import Path

_REFERENCE_CSV = Path(__file__).parent / "reference" / "team_abbreviations.csv"


@lru_cache(maxsize=1)
def load_abbreviation_to_team_id() -> dict[str, int]:
    """Return a dict mapping Statcast abbreviation -> numeric team_id.

    Cached for the process lifetime. Raises FileNotFoundError if the
    reference CSV is missing, since the replay cannot thread team_id
    without it.
    """
    if not _REFERENCE_CSV.exists():
        raise FileNotFoundError(
            f"Team abbreviation reference not found at {_REFERENCE_CSV}. "
            f"Run `python -m ingestion.replay_engine.build_team_abbreviation_map` "
            f"to generate it."
        )
    mapping: dict[str, int] = {}
    with _REFERENCE_CSV.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            mapping[row["abbreviation"]] = int(row["team_id"])
    return mapping


def abbreviation_to_team_id(abbreviation: str) -> int | None:
    """Look up a single abbreviation. Returns None if not found.

    A None return means the abbreviation was not in the reference map —
    the caller decides whether that is tolerable (it leaves team_id
    unset, projection is skipped) or an error.
    """
    return load_abbreviation_to_team_id().get(abbreviation)
