"""Pure matchup signal computation — no Pydantic, no I/O, no framework.

This module holds the signal logic that both the batch path and the
streaming path share: the calibrated magnitudes, the confidence-band
mapping, and compute_signal_fields, which turns a handedness matchup and
a lineup state into the three scalar fields the reconciliation layer
compares.

It is deliberately dependency-free (standard library only) so it can be
imported in any runtime. The batch path (signals.matchup_signal) imports
it and wraps the result in a Pydantic MatchupSignal model. The streaming
Flink UDF imports it directly — the Flink container has no Pydantic, and
the signal computation does not need it. Keeping this logic in one place
is the anti-drift guarantee of ADR 0001 and ADR 0021: both paths compute
the signal the same way because they call the same function.

Magnitudes come from signals.matchup_calibration, a module generated by
infra/data_prep/build_matchup_calibration.py from the 2024 full-season
Statcast pull with the delta method of The Book (Tango, Lichtman,
Dolphin). The audit trail — per-bucket splits, sample sizes, league
baseline — lives in dbt/seeds/matchup_calibration.csv, produced by the
same generator run. This replaced the ADR 0016 placeholders once the
full-season volume the Phase 3 validation required became available.
"""

from __future__ import annotations

from typing import Literal

from signals.matchup_calibration import CALIBRATED_SIGNAL_VALUES

# Mapping from lineup_state to confidence_band per ADR 0016.
_CONFIDENCE_BAND_BY_LINEUP_STATE: dict[str, Literal["full", "reduced", "suppressed"]] = {
    "confirmed": "full",
    "uncertain": "reduced",
    "projected": "suppressed",
}


def compute_signal_fields(
    handedness_matchup: str | None,
    lineup_state: str,
) -> tuple[float, str, str]:
    """The pure core of the matchup signal: the three scalar fields.

    Returns (signal_value, confidence_band, lineup_state_at_emission).
    No Pydantic dependency — plain dict lookups and a validation check.
    Both the batch path (generate_matchup_signal, which wraps the result
    in a MatchupSignal model) and the streaming path (the Flink UDF, which
    needs Flink-serializable scalars) call this core, so the two paths
    cannot drift and the streaming runtime needs no Pydantic.

    Raises ValueError if lineup_state is not one of the documented values.
    """
    if lineup_state not in _CONFIDENCE_BAND_BY_LINEUP_STATE:
        raise ValueError(
            f"unknown lineup_state {lineup_state!r}; "
            f"expected one of {sorted(_CONFIDENCE_BAND_BY_LINEUP_STATE)}"
        )
    signal_value = CALIBRATED_SIGNAL_VALUES.get(handedness_matchup, 0.0)
    confidence_band = _CONFIDENCE_BAND_BY_LINEUP_STATE[lineup_state]
    return (signal_value, confidence_band, lineup_state)


def derive_handedness_matchup(
    pitcher_handedness: str | None,
    batter_handedness: str | None,
) -> str | None:
    """Derive the handedness matchup string, matching the dbt model exactly.

    Mirrors the CASE in silver_matchup_events.sql:
        NULL if either side is NULL, else pitcher_hand || '_vs_' || batter_hand.

    So ('R', 'L') -> 'R_vs_L', ('R', 'S') -> 'R_vs_S', and a missing side
    (player absent from the handedness seed) -> None, since a partial
    matchup is not a usable signal. Both the batch path (dbt) and the
    streaming path (the Flink handedness UDF) derive the matchup the same
    way by calling this, so the two cannot drift — the same anti-drift
    guarantee compute_signal_fields gives for the signal itself
    (ADR 0001, ADR 0021).
    """
    if pitcher_handedness is None or batter_handedness is None:
        return None
    return f"{pitcher_handedness}_vs_{batter_handedness}"


def plan_signal_emissions(
    lineup_state: str,
    handedness_matchup: str | None,
    projected_handedness_matchup: str | None,
    has_projection: bool,
) -> list[tuple[str | None, str]]:
    """Decide how many signals a pitch emits, and from which inputs.

    Returns a list of (matchup, emission_lineup_state) pairs. Each pair is
    fed to compute_signal_fields to produce one signal row. This is the
    expansion logic of silver_matchup_signals (ADR 0020), factored out so
    the batch dbt model and the streaming Flink job plan emissions the
    same way and cannot drift. It decides only the expansion; the signal
    value itself comes from compute_signal_fields.

    Three cases, matching the documented emission model:

    - An uncertain pitch with a projection emits TWO signals: a reduced
      one from the projected handedness (what the system knew during the
      window, emitted as uncertain), and a full one from the real
      handedness (the resolution, emitted as confirmed). The reduced
      emission comes first so it sorts before the resolution.

    - An uncertain pitch with no projection emits ONE signal from the
      real handedness, still as uncertain — the system was in doubt but
      had nothing to project, so there is no second emission to confirm.

    - A confirmed pitch emits ONE signal from the real handedness, as
      confirmed.
    """
    if lineup_state == "uncertain" and has_projection:
        return [
            (projected_handedness_matchup, "uncertain"),
            (handedness_matchup, "confirmed"),
        ]
    # Confirmed, or uncertain-without-projection: a single emission using
    # the pitch's own lineup_state, so uncertain-without-projection still
    # records a reduced band honestly.
    return [(handedness_matchup, lineup_state)]
