"""Calibrated handedness-matchup magnitudes. GENERATED FILE -- DO NOT EDIT.

Generated by infra/data_prep/build_matchup_calibration.py. Audit trail
(per-bucket splits, sample sizes, league baseline) lives in
dbt/seeds/matchup_calibration.csv, produced by the same run. Data window:
2024-03-20 .. 2024-09-30, 181116 plate appearances. Sign convention
per ADR 0016: positive = pitcher advantage.

The switch-pitcher entries (S_vs_R, S_vs_L, S_vs_S) had no season data
and are NOT calibrated: they extend the measured map by the reasoning
the original placeholder documented -- a switch pitcher picks the
favorable side, so S_vs_R mirrors R_vs_R and S_vs_L mirrors L_vs_L,
with S_vs_S neutral. Regenerate this module by re-running the generator
with --module-out; do not edit values by hand.

The map holds exactly the nine handedness buckets. It carries no None key:
an irresolvable matchup (a player absent from the handedness seed) is not
a bucket with a neutral value -- it is the absence of a computable signal,
which compute_signal_fields represents by returning None rather than a
fabricated 0.0 (ADR 0028).
"""

from __future__ import annotations

CALIBRATED_SIGNAL_VALUES: dict[str, float] = {
    "R_vs_R": 0.0097,
    "R_vs_L": -0.0187,
    "L_vs_R": -0.0097,
    "L_vs_L": 0.0187,
    "R_vs_S": 0.0052,
    "L_vs_S": -0.0052,
    "S_vs_R": 0.0097,  # uncalibrated: mirrors R_vs_R (no season data)
    "S_vs_L": 0.0187,  # uncalibrated: mirrors L_vs_L (no season data)
    "S_vs_S": 0.0,  # uncalibrated: neutral (no season data)
}
